# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_script:
  - psql -c 'create database test;' -U postgres
after_success:
  - Rscript -e 'covr::codecov()'
